name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fonts
        run: |
          sudo apt update && sudo apt install ttf-mscorefonts-installer
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula
          select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer
          npm run build
      - name: Deploy site
        run: |
          npm run deploy
      - name: Status check
        uses: Sibz/github-status-action
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://openhps.org/