name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Build Website'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Install fonts
        run: |
          sudo apt update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installing Dependencies
        run: |
          npm install
      - name: Build site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build

  build_documentation:
    needs: build
    name: 'Build Documentation'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load documentation cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/docs
          key: ${{ runner.os }}-site-docs-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Build documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:docs

  build_ontology:
    needs: build
    name: 'Build Ontology'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load ontology cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/terms
            **/_ontology
          key: ${{ runner.os }}-site-ontology-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Build ontology
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:ontology
      
  build_presentations:
    needs: build
    name: 'Build Presentations'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load presentations cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/slides
          key: ${{ runner.os }}-site-presentations-v1-${{ hashFiles('**/_presentations.json') }}
      - name: Build presentations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:presentations

  deploy_github:
    needs:
      - build
      - build_documentation
      - build_presentations
      - build_ontology
    name: 'Deploy to Github Pages'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load documentation cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/docs
          key: ${{ runner.os }}-site-docs-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load presentations cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/slides
          key: ${{ runner.os }}-site-presentations-v1-${{ hashFiles('**/_presentations.json') }}
      - name: Load ontology cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/terms
            **/_ontology
          key: ${{ runner.os }}-site-ontology-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Deploy site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
      - name: Status check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Github Pages preview
          state: success
          target_url: https://openhps.github.io/openhps.org/

  deploy_netlify:
    needs:
      - build
      - build_documentation
      - build_presentations
      - build_ontology
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependecy cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load site cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site
            _presentations.json
          key: ${{ runner.os }}-site-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load documentation cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/docs
          key: ${{ runner.os }}-site-docs-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Load presentations cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/slides
          key: ${{ runner.os }}-site-presentations-v1-${{ hashFiles('**/_presentations.json') }}
      - name: Load ontology cache
        uses: actions/cache@v2
        with:
          path: |
            **/_site/terms
            **/_ontology
          key: ${{ runner.os }}-site-ontology-v1-${{ hashFiles('**/package-lock.json') }}
      - name: Deploy site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm run deploy
      - name: Status check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://openhps.org/