name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fonts
        run: |
          sudo apt update && sudo apt install -y ttf-mscorefonts-installer
      - name: Build site
        run: |
          npm install
          npm run build
      - name: Deploy site
        run: |
          npm run deploy
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Status check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://openhps.org/